# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id_key', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identification Key')),
                ('pos_name', models.CharField(max_length=100)),
                ('pos_desc', models.CharField(max_length=1000)),
                ('price_min', models.IntegerField()),
                ('price_growth', models.IntegerField()),
                ('price_start', models.IntegerField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('state', models.CharField(default='used', max_length=100)),
                ('pictures', models.CharField(default='prototyp', max_length=100)),
            ],
        ),
    ]
